[2022-09-17T17:35:46.604+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_Dataset_task manual__2022-09-17T17:35:44.441713+00:00 [queued]>
[2022-09-17T17:35:46.617+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_Dataset_task manual__2022-09-17T17:35:44.441713+00:00 [queued]>
[2022-09-17T17:35:46.618+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-17T17:35:46.619+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2022-09-17T17:35:46.619+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-17T17:35:46.637+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): download_Dataset_task> on 2022-09-17 17:35:44.441713+00:00
[2022-09-17T17:35:46.645+0000] {standard_task_runner.py:52} INFO - Started process 87 to run task
[2022-09-17T17:35:46.652+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_Dataset_task', 'manual__2022-09-17T17:35:44.441713+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp2s2rdulm', '--error-file', '/tmp/tmpwhs9df20']
[2022-09-17T17:35:46.655+0000] {standard_task_runner.py:80} INFO - Job 71: Subtask download_Dataset_task
[2022-09-17T17:35:46.773+0000] {task_command.py:371} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_Dataset_task manual__2022-09-17T17:35:44.441713+00:00 [running]> on host 62bee0f86eda
[2022-09-17T17:35:46.894+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_Dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-17T17:35:44.441713+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-17T17:35:44.441713+00:00
[2022-09-17T17:35:46.909+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 28, in download_from_drive
    gdown.download(url, output, quiet=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/gdown/download.py", line 120, in download
    os.makedirs(cache_dir)
  File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/airflow/.cache/gdown'
[2022-09-17T17:35:46.926+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=download_Dataset_task, execution_date=20220917T173544, start_date=20220917T173546, end_date=20220917T173546
[2022-09-17T17:35:46.941+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 71 for task download_Dataset_task ([Errno 13] Permission denied: '/home/airflow/.cache/gdown'; 87)
[2022-09-17T17:35:46.986+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-17T17:35:47.037+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
